name: dreamcatcher
channels:
  - conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - fastapi
  - uvicorn
  - sqlalchemy
  - psycopg2
  - geoalchemy2
  - websockets
  - pydantic
  - python-dotenv
  - pytest
  - requests
  - shapely
  - pyproj
  - pillow
  - bcrypt
  - pip:
    - httpx
    - postgis
    - fastmcp
    - pytest-asyncio
    - websocket-client
    - pydantic-settings
    - pytest-cov
    - python-jose[cryptography]
    - pydantic[email]
    - SimpleLLMFunc
    - duckduckgo-search==7.5.5
